version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: sudo install  
      timeout: 300
      runas: root
  ApplicationStart:
    - location: sudo start
      timesout: 300
      runas: root     
