version: 0.0
os: ubuntu
files:
  - source: /appspec.yml
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: start
      timesout: 300
      runas: root     
